### PR TITLE
Adding Dagger to the list in README

### PR DESCRIPTION
**Pull request by patkivikram**
Adding Dagger to the README

### CODE REVIEW

**Comment by patkivikram** [comment]
@meirwah  we just open sourced it, but we have been using it widely for about 2 years. Looking to benefit from community support at this point

**Comment by patkivikram** [comment]
This library is maintained by the engineering team at Wayfair

**Comment by patkivikram** [comment]
@meirwah could we merge this one, please?

**Comment by meirwah** [comment]
Hey @patkivikram I understand this is maintained , but I want to see some OSS traction before adding to this list

since it has only 3 github stars, I want to wait until it reaches a much higher number, than I will add

For now I will close this PR, feel free to reopen once Dagger repo reaches a more significant amount of github stars , which is a key metric to asses the project

**Comment by patkivikram** [comment]
hey @meirwah do you think we can add it now? This is more of a chicken and egg problem

**Review by meirwah — APPROVED** [review]

**Pull request merged**
