### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Marco-Sulla**
Camunda and Flowable are forks of Activiti, so all three can be used as a library for a Spring projects.

Added YAWL, buggy, unsupported, dead project, but with really interesting features and much more simple to use.

### CODE REVIEW

**Comment by meirwah** [comment]
Hey @Marco-Sulla ,
Not sure about this PR, I prefer to keep  Camunda and Flowable are forks of Activiti, under BPMN part, because this (IMO) is a stronger feature of this projects.

About YAWL, from what you say, it doesn't seem so "awesome" , so don't think it's worth adding...

**Comment by rsoika** [comment]
Your thoughts about 'awesome' is a good point.
If we add any kind of project which is in some kind related to "workflow" the list will become difficult to read for prospects. 
Of course every product owner is convinced that his own project is 'awesome'  - me too ;-) 
But how can we help the prospect in this question....?

**Comment by meirwah** [comment]
I mainly look when it's an OSS project, on the amount of github stars and if the project is maintained, 
in this case YAWL has only 35 stars (while it's from 4 years ago) and doesn't seem to be maintained for past 2 years

**Comment by Marco-Sulla** [comment]
About Activiti, Camunda and Flowable, all three are BPMN workflow managers and all three can be integrated in a Spring (Boot) application. So I think they should be in the same section, or in the same two sections...

About YAWL, yes, I confirm all the problems of that application. But it's particular, because it's the only workflow manager that I know that is based on the Petri net. Furthermore is much more easy to use than Activiti and sons, and has a strong validation tool. Furthermore, it generated forms for user task automatically.

**Pull request closed without merging**
