### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by c2u5hed**

### CODE REVIEW

**Comment by meirwah** [comment]
10x for addition!
But please note this list is Ordered by alphabetical order, can you put it in the right place?

**Comment by c2u5hed** [comment]
Thanks)

It seems that I've put it in correct order. 'Workflow Engine' starts with W, which means it should be in the end of your list. Shouldn't it?

**Comment by meirwah** [comment]
your'e right :) missed that for a moment..

**Comment by meirwah** [comment]
But the way, you know why are they using XML instead of json for import/export?

**Comment by c2u5hed** [comment]
For popularity reasons, I think. Back in 2011 when they started XML was mainstream. Hopefully, they'll release a json option as well in newer builds

**Pull request merged**
